Delete DYP_STAKING_GOVERNANCE_AUDIT_1.2.pdf
dypfinance/staking-governance-security-audits pull request #12
Opened 2021-03-13 00:11 UTC by hakanabasi

2021-03-13 00:16 UTC, hakanabasi commented
https://github.com/dypfinance/staking-governance-security-audits/pull/12#issue-592228354

2021-03-13 19:41 UTC, bacdayhx commented
Ok

2021-03-14 05:18 UTC, Psyruss77 approved these changes

2021-03-15 18:55 UTC, hainusii requested changes
[DYP_STAKING_GOVERNANCE_AUDIT (1) (1) (1).pdf](https://github.com/dypfinance/staking-governance-security-audits/files/6143805/DYP_STAKING_GOVERNANCE_AUDIT.1.1.1.pdf)

2021-03-20 14:15 UTC, closed without merging